<a href="https://colab.research.google.com/github/KashishTiwari-17/OIBSIP_Data-Science_task1/blob/main/task1%5Biris_classification%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib
import warnings
warnings.filterwarnings("ignore")

# Load dataset
df = pd.read_csv('/content/Iris.csv')
print("📊 Sample Data:\n", df.head())

# Drop Id column if present
if 'Id' in df.columns:
    df.drop('Id', axis=1, inplace=True)

# Encode target column
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])

# Features and target
X = df.drop('Species', axis=1)
y = df['Species']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model training
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Evaluation
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"\n✅ Model Accuracy: {accuracy * 100:.2f}%")
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le.classes_))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Save the model and label encoder
joblib.dump(model, 'iris_classifier.pkl')
joblib.dump(le, 'label_encoder.pkl')
print("\n✅ Model saved as 'iris_classifier.pkl'")

# Function for prediction based on user input
def predict_iris():
    print("\n🌸 Enter flower measurements to predict the Iris species:")

    try:
        sl = float(input("Sepal Length (cm): "))
        sw = float(input("Sepal Width (cm): "))
        pl = float(input("Petal Length (cm): "))
        pw = float(input("Petal Width (cm): "))
    except ValueError:
        print("❌ Invalid input! Please enter numeric values.")
        return

    user_data = np.array([[sl, sw, pl, pw]])
    prediction = model.predict(user_data)[0]
    predicted_class = le.inverse_transform([prediction])[0]

    print(f"\n🌼 Predicted Iris Species: {predicted_class}")

# Run prediction loop
if __name__ == "__main__":
    while True:
        predict_iris()
        cont = input("\nPredict another flower? (y/n): ").lower()
        if cont != 'y':
            print("👋 Thank you for using the Iris Classifier!")
            break


📊 Sample Data:
    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

✅ Model Accuracy: 100.00%

Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

✅ Model sav